swagger: '2.0'
info:
  title: 'Device Capturing Stream API'
  description: 'Information about the pets in your garden'
  contact:
    name: 'erkennen codieren pakete'
    email: erkennen.codieren.pakete@post.ch
    version: '@version@'
  version: 0.1.0-rc.1
host: 'server:8080'
basePath: MQTT
paths:
  '{sortingUnitKey}/reading/v1/coding/capture-request/{srcSystem}/{srcInstance}/{dstSystem}/{dstInstance}/{conversationId}':
    get:
      summary: 'VOL-Scanner Capture-Request'
      description: 'Requests the physical properties, images and barcodes of a mailpiece'
      tags:
        - MQTT
      parameters:
        -
          name: sortingUnitKey
          in: path
          description: 'Identifier of the sorting unit'
          type: string
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: VOL
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '001'
        -
          name: destSystem
          in: path
          description: '3-letter uppercase name identifying the system receiving the message'
          type: string
          default: MMCB
        -
          name: destInstance
          in: path
          description: 'two-digit padded number identifying the system instance receiving the message'
          type: string
          default: WHR01
        -
          name: conversationId
          in: path
          description: 'ID included in the read-event and request-status topics in order to correlate the messages'
          type: string
          default: '12345'
      responses:
        default:
          schema: {$ref: 'CaptureRequest'}
    x-data:
      classification: P0
      confidentiality: C2
  '{sortingUnitKey}/reading/v1/coding/capture-result/{srcSystem}/{srcInstance}/{dstSystem}/{dstInstance}/{conversationId}':
    get:
      summary: 'VOL-Scanner Capture-Result'
      description: 'Sends a result of the physical properties, images and barcodes of a mailpiece'
      tags:
        - MQTT
      parameters:
        -
          name: sortingUnitKey
          in: path
          description: 'Identifier of the sorting unit'
          type: string
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: VOL
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '001'
        -
          name: destSystem
          in: path
          description: '3-letter uppercase name identifying the system receiving the message'
          type: string
          default: MMCB
        -
          name: destInstance
          in: path
          description: 'two-digit padded number identifying the system instance receiving the message'
          type: string
          default: WHR01
        -
          name: conversationId
          in: path
          description: 'ID included in the read-event and request-status topics in order to correlate the messages'
          type: string
          default: '12345'
      responses:
        default:
          schema: {$ref: 'CaptureResult'}
    x-data:
      classification: P0
      confidentiality: C2
definitions:
  CaptureData:
    type: object
    properties:
      state:
        $ref: 'State'
        description: 'The state of the result.'
      source:
        $ref: 'Source'
        description: 'The system, which publishes the event.'
      images:
        $ref: 'Images'
        description: 'The images captured during coding.'
      dimension:
        $ref: 'Dimension'
        description: 'Dimension of the mailpiece.'
    required:
      - state
      - source
    additionalProperties: false
  DateTime:
    type: string
    description: "<a href=\"https://swagger.io/docs/specification/data-models/data-types/#string\">String @format date-time</a>,\nas defined by <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6</a>,\nfor example: <code>2014-05-22T10:42:42.542+00:00</code>."
    format: date-time
  Int:
    type: integer
    description: '<a href="https://swagger.io/docs/specification/data-models/data-types/#numbers">Number @asType integer</a>'
  CaptureRequest:
    type: object
    properties:
      timestamp:
        $ref: 'DateTime'
        description: 'The timestamp of the message.'
      requestedCapabilities:
        $ref: 'RequestedCapabilities'
        description: 'The requested Capabilities.'
      conveyingAidHeight:
        $ref: 'Int'
        description: 'The height of the conveying aid in mm which has to be subtracted from the measured value.'
    required:
      - timestamp
      - requestedCapabilities
    additionalProperties: false
  CaptureResult:
    type: object
    properties:
      timestamp:
        $ref: 'DateTime'
        description: 'The timestamp of the message.'
      processingItemId:
        type: string
        description: "Identifier generated by the sorting unit for one sorting cycle. This id is only valid during the\nsorting cycle and might be reused by the sorting unit quickly for a next sorting cycle.\nTo correlate event to one sorting cycle use the sortingCycleId."
      sortingUnit:
        $ref: 'SortingUnit'
        description: 'Unique key identifying the location.'
      captureData:
        $ref: 'CaptureData'
        description: 'Data captured by the MMCB station.'
    required:
      - timestamp
      - processingItemId
      - sortingUnit
      - captureData
    additionalProperties: false
  Dimension:
    type: object
    properties:
      length:
        type: string
        description: 'Length of the mailpiece in millimeters.'
      width:
        type: string
        description: 'Width of the mailpiece in millimeters.'
      height:
        type: string
        description: 'Height of the mailpiece in millimeters.'
    additionalProperties: false
  Images:
    type: object
    properties:
      imageId:
        type: string
        description: 'Identifier of the image. Multiple messages can refer to the same image.'
      groupId:
        type: string
        description: "Image Group ID;\nMultiple messages can refer to a single groupId\nin case there are multiple faces in the group."
      url:
        type: string
        description: 'URL to the image.'
    additionalProperties: false
  Producer:
    type: string
    enum:
      - MANUAL_CODING_BULK
      - VOLUME_SCANNER
    description: "MANUAL_CODING_BULK - Component where barcodes, weight, dimensions and address information are captured or entered (manually or partially automated).\nVOLUME_SCANNER - Component where the dimensions and images are captured."
  RequestedCapabilities:
    type: object
    properties:
      measureDimensions:
        type: boolean
        description: 'The id.'
      captureImage:
        type: boolean
        description: 'The given name.'
    required:
      - measureDimensions
      - captureImage
    additionalProperties: false
  SortingUnit:
    type: object
    properties:
      sortingUnitKey:
        type: string
        description: 'Unique identifier of the sorting unit at a specific location.'
      locationKey:
        type: string
        description: 'Unique key identifying the location.'
    required:
      - sortingUnitKey
      - locationKey
    additionalProperties: false
  Source:
    type: object
    properties:
      producer:
        $ref: 'Producer'
        description: 'Device, which provided the information.'
      instance:
        type: string
        description: 'Instance of the device.'
    required:
      - producer
      - instance
    additionalProperties: false
  State:
    type: string
    enum:
      - OK
      - ERROR
    description: "OK - The request has been processed successfully.\nERROR - The result led to an error."
